# We don't need this because its in the package.json
# but we set it anyway just to make sure we know what is what
name: "@phpsa/lando-db-tools"

# Let lando autoscan this plugin for "legacy" plugin stuff needed for v3
legacy: true
